### ISSUE TITLE
No data Returned

### ISSUE THREAD

**Issue by drak42** [ideasdelivery/tzsp-reader#2]
Hi,

This looks very interesting!

I have tried to set it up but am getting nothing other than a "uses" counter for IPV4 incrmenting.

I can see detail when i check the Mikrotik Packet Sniffer Packers/Connections etc.

What am I missing?

Cheers
Chris

**Comment by ivanhuay** [comment]
Can you describe the problem better? of the 4 tabs you can only see the packet counter?

which os are you using?

in mikrotik web interface the path url is  /webfig/#Tools:Packet_Sniffer

there you would have to add the ip of the server and push the apply and start button

any problem send a screenshot so I can help you better

**Comment by BrunIF** [comment]
Why is the other window empty?
 ![2017-10-29 23 02 17](https://user-images.githubusercontent.com/490917/32148290-447309c8-bcfd-11e7-8275-c08840c1aa12.png)

**Comment by ivanhuay** [comment]
@BrunIF what configuration you have packet sniffer of mikrotik?

this is my configuration in the web interface from mikrotik

![mikrotik_conf](https://user-images.githubusercontent.com/5782286/32626781-0cfa2754-c56f-11e7-859c-1602498c701d.png)

**Comment by BrunIF** [comment]
Sorry. My mistake. Working fine. 
But can you describe (in wiki) step by step how to configure mikrotik?

**Comment by BrunIF** [comment]
@drak42 
Create in directory file ipfile.json

Example:
```json
{
    "192.168.1.1":   "User 1",
    "192.168.1.2":   "User 2",
    "192.168.1.3":   "User 3",
    "192.168.1.4":   "User 4",
    "192.168.1.5":   "User 5"
}
```

**Comment by ivanhuay** [comment]
the .ipfile.json file already existed but add example-ipfile.json to leave in gitignore to ipfile.json

**Comment by ivanhuay** [comment]
here create the wiki with the [configuration](https://github.com/gravadigital/tzsp-reader/wiki/Mikrotik-Configuration) detail of mikrotik. I'm going to close the issue
